default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") { "root" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "hasanitki" } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "sewakasur_development" } %>

test:
  <<: *default
  database: sewakasur_test

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "sewakasur_production" } %>

