default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: hasanitki
  host: localhost

development:
  <<: *default
  database: sewakasur_development

test:
  <<: *default
  database: sewakasur_test

production:
  <<: *default
  database: sewakasur_production

